#!/usr/bin/env node
//
// Produces the example fixtures and their golden geometry.
//
//   cd tools && npm install && node generate_golden.mjs
//
// The golden geometry is generated by running the real chartjs-chart-sankey
// library over each dataset, not by running this project's Python. That is the
// point: a golden produced by the code under test proves nothing. This tool
// exists so the goldens stay regenerable rather than becoming opaque blobs
// nobody can rebuild.
//
// Nothing in this directory is ever installed. The wheel ships only
// `src/sankey_mpl`, so this file cannot reach site-packages and `pip install` never
// brings Node anywhere near you.
//
// It *is* shipped in the sdist though, along with `tools/datasets/`, and that is
// deliberate rather than an oversight: a source release that could not rebuild its
// own goldens would leave them unverifiable blobs. Shipped for reproducibility, not
// for use at runtime. See the sdist comment in pyproject.toml.
//
// CI does not run this. Node and npm are only needed if you are changing a dataset.
//
// Writes, relative to the repository root:
//   tests/data/datasets.json       the manifest conftest parametrises over
//   tests/data/<key>.json          links, labels and colours — the library's input
//   tests/data/<key>-golden.json   geometry chartjs-chart-sankey resolved
//
import { readFileSync, writeFileSync, mkdirSync, readdirSync, unlinkSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { createCanvas } from "@napi-rs/canvas";
import { Chart, registerables } from "chart.js";
import { SankeyController, Flow } from "chartjs-chart-sankey";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const SPECS = join(HERE, "datasets");
const OUT = join(ROOT, "tests", "data");

// Categorical hues in fixed order, validated for colour-vision deficiency
// separation against a light surface (worst adjacent pair ΔE 15.7 deutan). The
// order is part of the contract: hues are assigned by first appearance and never
// cycled, so a dataset with more nodes in its `colorBy` layer than there are
// slots is an error rather than a silent repeat.
const PALETTE = ["#3F9C35", "#7A4FA3", "#E8730C", "#1F6FB2", "#C7302B", "#0E8F9E"];

// Not a categorical slot — the neutral for structural nodes. Keeping grey out of
// the rotation is what stops it colliding with the teal.
const NEUTRAL = "#8A94A0";

Chart.register(...registerables, SankeyController, Flow);

const grouped = (value) => value.toLocaleString("en-US");

const upstreamVersion = (pkg) =>
  JSON.parse(readFileSync(join(HERE, "node_modules", pkg, "package.json"), "utf8"))
    .version;

/**
 * Expand a dataset's rows into nodes and links.
 *
 * Every row is a full path from the source to a terminal node, so each row adds
 * its flow to every hop it implies. Two properties fall out of that and both are
 * relied on by the tests: flow is conserved end to end, and there is exactly one
 * column-0 node. Node keys are prefixed with their layer name, which is what
 * keeps two layers that happen to share a hop name from being merged into one
 * node — that merge would manufacture a backward link and the guards would
 * (correctly) reject the whole dataset.
 */
function expand(spec) {
  const { source, layers, rows } = spec;
  const [sourceLayer, ...hopLayers] = layers;

  const linkTotals = new Map();
  const nodeTotals = new Map();
  const addLink = (from, to, flow) => {
    const key = `${from} ${to}`;
    linkTotals.set(key, (linkTotals.get(key) || 0) + flow);
  };
  const addNode = (key, flow) => nodeTotals.set(key, (nodeTotals.get(key) || 0) + flow);

  for (const row of rows) {
    if (row.path.length !== hopLayers.length) {
      throw new Error(
        `${spec.key}: path [${row.path}] has ${row.path.length} hops but ` +
          `${hopLayers.length} layers follow the source`,
      );
    }
    const keys = [
      `${sourceLayer}:${source}`,
      ...row.path.map((hop, index) => `${hopLayers[index]}:${hop}`),
    ];
    addNode(keys[0], row.flow);
    for (let i = 0; i < keys.length - 1; i += 1) {
      addLink(keys[i], keys[i + 1], row.flow);
      addNode(keys[i + 1], row.flow);
    }
  }

  // First-appearance order, and it matters: link order is the last tie-break in
  // the layout, so a fixture must record the exact order used for its golden.
  const links = [...linkTotals.entries()].map(([key, flow]) => {
    const [from, to] = key.split(" ");
    return { from, to, flow };
  });

  return { links, nodeTotals };
}

function colorResolver(spec) {
  const { colors } = spec;
  const palette = colors.palette || PALETTE;
  const fallback = colors.default || NEUTRAL;
  const assigned = new Map();
  let next = 0;

  return (key) => {
    if (colors.overrides && key in colors.overrides) return colors.overrides[key];
    const layer = key.slice(0, key.indexOf(":"));
    if (layer === colors.colorBy) {
      if (!assigned.has(key)) {
        if (next >= palette.length) {
          throw new Error(
            `${spec.key}: layer "${layer}" has more nodes than the ${palette.length}` +
              ` palette slots. Hues are never cycled — split the layer or supply` +
              ` a longer "palette".`,
          );
        }
        assigned.set(key, palette[next]);
        next += 1;
      }
      return assigned.get(key);
    }
    if (colors.layers && layer in colors.layers) return colors.layers[layer];
    return fallback;
  };
}

function buildNodes(spec, nodeTotals) {
  const color = colorResolver(spec);
  const unit = spec.unit ?? "";
  const nodes = {};
  for (const [key, total] of nodeTotals) {
    const name = spec.names[key];
    if (name === undefined) throw new Error(`${spec.key}: no name for node "${key}"`);
    nodes[key] = { label: `${name} (${grouped(total)}${unit})`, color: color(key) };
  }
  return nodes;
}

/** Run the reference implementation and record the geometry it resolves. */
function runReference(spec, nodes, links) {
  const color = (key) => nodes[key].color;
  const labels = Object.fromEntries(
    Object.entries(nodes).map(([key, node]) => [key, node.label]),
  );
  const canvas = createCanvas(spec.render.cssWidth, spec.render.cssHeight);
  const chart = new Chart(canvas, {
    type: "sankey",
    data: {
      datasets: [
        {
          data: links,
          labels,
          colorFrom: (c) => color(c.dataset.data[c.dataIndex].from),
          colorTo: (c) => color(c.dataset.data[c.dataIndex].to),
          colorMode: "gradient",
          alpha: 0.5,
          size: "max",
        },
      ],
    },
    options: {
      responsive: false,
      animation: false,
      devicePixelRatio: spec.render.devicePixelRatio,
      plugins: { legend: { display: false }, tooltip: { enabled: false } },
    },
  });

  const meta = chart.getDatasetMeta(0);
  const controller = meta.controller;
  const resolved = controller.options;

  const offsetOf = (refs, key, index) => {
    for (const ref of refs) if (ref.key === key && ref.index === index) return ref.addY;
    return 0;
  };

  const golden = {
    generatedBy: "tools/generate_golden.mjs",
    key: spec.key,
    title: spec.title,
    upstream: {
      library: "chartjs-chart-sankey",
      version: upstreamVersion("chartjs-chart-sankey"),
      chartjs: upstreamVersion("chart.js"),
    },
    // What the reference was rendered at. The gap the reference produces depends
    // on the backing-store height, so a comparison has to know these.
    render: {
      cssWidth: chart.width,
      cssHeight: chart.height,
      devicePixelRatio: spec.render.devicePixelRatio,
      backingStoreHeight: canvas.height,
      nodeWidth: resolved.nodeWidth,
      nodePadding: resolved.nodePadding,
      borderWidth: resolved.borderWidth,
      padding: { top: 3, right: 13, bottom: 3, left: 3 },
    },
    maxColumn: controller._maxX,
    totalHeight: controller._maxY,
    chartArea: {
      left: chart.chartArea.left,
      right: chart.chartArea.right,
      top: chart.chartArea.top,
      bottom: chart.chartArea.bottom,
    },
    nodes: Object.fromEntries(
      [...controller._nodes.values()].map((n) => [
        n.key,
        { column: n.x, y: n.y, size: n.size, inflow: n.in, outflow: n.out },
      ]),
    ),
    links: links.map((link, index) => {
      const element = meta.data[index];
      const from = controller._nodes.get(link.from);
      return {
        from: link.from,
        to: link.to,
        flow: link.flow,
        offset: offsetOf(from.to, link.to, index),
        x: element.x,
        x2: element.x2,
        y: element.y,
        y2: element.y2,
        height: element.height,
      };
    }),
  };

  chart.destroy();
  return golden;
}

// ---- main ----------------------------------------------------------------- //

const { datasets: keys } = JSON.parse(readFileSync(join(SPECS, "index.json"), "utf8"));

mkdirSync(OUT, { recursive: true });

// Clear derived files so a removed dataset cannot linger and keep passing.
for (const name of readdirSync(OUT)) {
  if (name.endsWith(".json")) unlinkSync(join(OUT, name));
}

const manifest = [];
for (const key of keys) {
  const spec = JSON.parse(readFileSync(join(SPECS, `${key}.json`), "utf8"));
  if (spec.key !== key) throw new Error(`${key}.json declares key "${spec.key}"`);

  const { links, nodeTotals } = expand(spec);
  const nodes = buildNodes(spec, nodeTotals);
  const golden = runReference(spec, nodes, links);

  writeFileSync(
    join(OUT, `${key}.json`),
    JSON.stringify({ key, title: spec.title, nodes, links }, null, 2) + "\n",
  );
  writeFileSync(join(OUT, `${key}-golden.json`), JSON.stringify(golden, null, 2) + "\n");

  // Whether reversing the link list changes this dataset's layout. A property of
  // the Python layout rather than of the reference, so it is declared in the spec
  // and asserted by the tests instead of being computed here — computing it from
  // the code under test is exactly the circularity the goldens exist to avoid.
  if (typeof spec.orderSensitive !== "boolean") {
    throw new Error(`${key}.json must declare "orderSensitive" as a boolean`);
  }

  manifest.push({
    key,
    title: spec.title,
    blurb: spec.blurb,
    orderSensitive: spec.orderSensitive,
    // Cosmetic, for render_previews.py only. Deliberately not the same as the
    // golden's render settings, which are a test concern.
    preview: { width: spec.preview.width, height: spec.preview.height },
    nodes: Object.keys(nodes).length,
    links: links.length,
    maxColumn: golden.maxColumn,
  });

  console.log(
    `${key.padEnd(10)} ${String(links.length).padStart(3)} links  ` +
      `${String(Object.keys(nodes).length).padStart(3)} nodes  ` +
      `maxColumn ${golden.maxColumn}  totalHeight ${golden.totalHeight}`,
  );
}

writeFileSync(
  join(OUT, "datasets.json"),
  JSON.stringify({ generatedBy: "tools/generate_golden.mjs", datasets: manifest }, null, 2) +
    "\n",
);

console.log(`\nwrote ${manifest.length} datasets to tests/data/`);
